sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: admin
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tR3hGUfk4vgU4ofHVZP
    access-key-secret: XzkmlWpCgm4kW6vvFNfDwuXA9HcSqt
    bucket-name: xie-ssm-sky-takeout
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
